name: Rent Reminder

on:
  schedule:
    - cron: "35 11 * * *"  # Runs every day at 9:00 AM UTC
  workflow_dispatch:     # Manual trigger

jobs:
  send-reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}" >> .env
        echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
        echo "TO_EMAIL=${{ secrets.TO_EMAIL }}" >> .env

    - name: Run script
      run: python rent_reminder.py
